# Docs: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
    -   package-ecosystem: "pip"
        directory: "/"
        schedule:
            interval: "daily"
        assignees:
            - "ManuelArcieri"
        reviewers:
            - "ManuelArcieri"

    -   package-ecosystem: "npm"
        directory: "/website"
        schedule:
            interval: "daily"
        assignees:
            - "ManuelArcieri"
        reviewers:
            - "ManuelArcieri"
